config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

::Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  root 'projects#index'

  mount ::Sidekiq::Web => '/sidekiq', constraints: ::Session::RouteConstraint.new(:root?)

  %i[about docs home transparency privacy].each do |link|
    direct "links_#{link}" do |options|
      ::APP_SETTINGS.dig(:links, link) || options[:fallback] || '#'
    end
  end

  concern :gpg_keys do
    get 'gpg_key', to: 'gpg_keys#index', as: :index_gpg_key
    post 'gpg_key/generate', to: 'gpg_keys#generate', as: :generate_gpg_key
    post 'gpg_key/upload', to: 'gpg_keys#upload', as: :upload_gpg_key
    delete 'gpg_key/destroy', to: 'gpg_keys#destroy', as: :destroy_gpg_key
  end

  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy] do
    delete 'destroy_all_but_current', on: :collection
  end
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[edit create]
    resource :password_reset,     only: %i[new edit create update]
    resource :account,            only: %i[show update]
  end

  scope '/account' do
    concerns :gpg_keys
  end

  namespace :agent_api do
    post '/', to: 'api#call'
    # get '/sources_tarball/:task_id', to: 'api#sources_tarball', as: 'download_sources_tarball'
    post '/artefacts/:task_id', to: 'api#upload_artefact', as: 'upload_artefact'
  end

  resources :projects do
    resources :ssh_keys, only: %i[create] do
      post :copy, on: :collection
    end
    resources :sources, only: %i[index create]
    resources :webhooks, only: %i[index create show new update destroy]
    resource :custom_repository_storage, only: %i[create update show destroy]
  end

  resources :agents
  resources :tasks, only: %i[index show create destroy] do
    get 'log', on: :member
    post 'cancel', on: :member
    post 'publish', on: :member
  end
  resources :repositories, only: %i[index show destroy] do
    concerns :gpg_keys
  end

  get ':user_slug/:project_slug', to: 'installs#index', as: 'package_install'
  get ':user_slug/:project_slug/install', to: redirect('%{user_slug}/%{project_slug}')

  post 'inbound_webhooks/:key', to: 'inbound_webhooks#trigger', as: 'trigger_webhook'

  ::PagesController::ALL.each do |page|
    get page, to: "pages##{page}", as: "pages_#{page}"
  end
  get 'distros/deprecated/:id', to: 'pages#deprecated_distro', as: :deprecated_distro_path
end

app/models/repository.rb
class Repository < ::ApplicationRecord
  belongs_to :project, class_name: '::Project', inverse_of: :repositories
  has_one :user, through: :project, class_name: '::User'

  validates :distro_id, inclusion: { in: ::Distro.ids }
  validates :gpg_key_private, :gpg_key_public, presence: true, allow_nil: true

  encrypts :gpg_key_private, :secret_access_key

  enum :publish_status, %w[pending publishing published].index_with(&:itself), default: 'pending'

  broadcast_with ::Broadcasts::Repository

  after_destroy_commit { ::DeleteFilesJob.perform_later(storage_config.client_config, storage_config.bucket, storage_config.path) }

  scope :without_own_gpg_key, -> { where(gpg_key_private: nil, gpg_key_public: nil) }
  scope :with_own_gpg_key, -> { where('gpg_key_private IS NOT NULL AND gpg_key_public IS NOT NULL') }
  scope :ordered, -> {
    ids = ::Distro.ids
    order(::Arel.sql("CASE #{ids.map { "WHEN distro_id = ? THEN ?" }.join(' ')} ELSE 10000 END", *ids.map.with_index.to_a.flatten))
  }
  scope :by_package_type, ->(pkg) { where(distro_id: ::Distro.by_package_type(pkg.to_s).map(&:id)) }

  def distro
    ::Distro[distro_id]
  end

  def distro=(dist)
    self.distro_id = dist.id
  end

  def storage
    ::Repository::Storage.new(storage_config)
  end

  def storage_config
    project.repository_storage_config.append_path(distro.slug)
  end

  def gpg_key
    if with_own_gpg_key?
      ::Gpg::Key[gpg_key_private, gpg_key_public]
    else
      user.gpg_key
    end
  end

  def with_own_gpg_key?
    gpg_key_private.present? && gpg_key_public.present?
  end

  def package_name
    project.package_name(distro.id)
  end

  def installable_cli
    distro.install_steps.map do |command|
      format(command, project_slug: project.slug, package_name:, url: storage.url)
    end.join("\n")
  end

  def installable_file_url
    return unless installable_filename

    storage_config.append_path(installable_filename).url
  end

  def humanized_name
    "#{project.name} / #{distro.name}"
  end
end

app/models/repository/publish.rb
class Repository
  class Publish
    attr_reader :repository

    def initialize(repository)
      @repository = repository
      @logger = ::ActiveSupport::TaggedLogging.new(::Rails.logger)
    end

    def call(artefacts) # rubocop: disable Metrics/AbcSize, Metrics/MethodLength
      logger.tagged('publish', "repo=#{repository.id}", "project=#{repository.project.id}", "distro=#{repository.distro.id}") do
        logger.info('start')

        repository.publishing!
        storage.create_bucket_if_not_exists!

        installable_filename = nil
        ::Dir.mktmpdir do |dir|
          synced_artefacts = sync_repo_files(artefacts, dir)
          installable_filename = extract_installable_filename(dir, synced_artefacts)
          logger.info("finish\n#{::ShellUtil.execute("tree #{dir}").out}")
        end
        repository.update!(published_at: ::Time.now.utc, last_publish_error: nil, publish_status: 'published', installable_filename:)
        repository.project.badge.generate_and_upload
      rescue ::StandardError => e
        logger.info("error: #{e.message}")
        repository.update!(last_publish_error: e.message, publish_status: 'pending')
        raise
      end
    end

    private

    attr_reader :logger

    delegate :storage, to: :repository

    def sync_repo_files(artefacts, dir)
      suitable_artefacts = artefacts.select { |i| i.filetype == repository.distro.package_type }
      return if suitable_artefacts.empty?

      # storage.download_all(to: dir)
      suitable_artefacts.each { |i| i.download(to: dir, overwrite_existing: true) }

      build_repo_manage(dir).sync

      storage.upload_all(from: dir)
      storage.delete_deleted_files(from: dir)

      suitable_artefacts
    end

    def build_repo_manage(dir)
      ::RepoManage::Repo.new(
        runtime:      build_runtime(dir),
        type:         repository.distro.package_type,
        gpg_key:      repository.gpg_key,
        project_slug: repository.project.slug,
        distro_name:  repository.distro.name,
        distro_url:   storage.url
      )
    end

    def build_runtime(workdir)
      ::RepoManage::Runtime.new(
        executable: ::APP_SETTINGS.fetch(:container_runtime),
        workdir:    workdir,
        image:      repository.distro.image,
        setup_cli:  repository.distro.setup_repo
      )
    end

    def extract_installable_filename(dir, synced_artefacts)
      return unless synced_artefacts

      installable_filename = synced_artefacts.map(&:filename).find { _1.include?(repository.package_name) }
      result = ::Dir.glob(dir + '/**/*').find { ::File.basename(_1) == installable_filename }
      result.gsub(dir, '')
    end
  end
end

app/models/repository/storage.rb
class Repository
  class Storage
    FileItem = ::Data.define(:key, :size, :last_modified_at, :url)

    Config = ::Data.define(:client_config, :bucket, :bucket_public_url, :path) do
      def self.default
        new(
          client_config: ::StorageClient::Config.default,
          bucket: ::APP_SETTINGS.fetch(:repositories).fetch(:bucket),
          bucket_public_url: ::APP_SETTINGS.fetch(:repositories).fetch(:bucket_public_url, nil),
          path: ''
        )
      end

      def append_path(*arg)
        self.class.new(client_config:, bucket:, bucket_public_url:, path: ::PathUtil.join(path, *arg))
      end

      def url
        url_to_public(client_config.build_url(bucket, path))
      end

      def url_to_public(arg)
        return arg if bucket_public_url.blank?

        private_url = client_config.build_url(bucket)
        arg.gsub(private_url, bucket_public_url)
      end
    end

    attr_reader :client, :config

    delegate :bucket, :path, :url, to: :config

    def initialize(config)
      @config = config
      @client = ::StorageClient.new(config.client_config)
      freeze
    end

    def ping!
      client.ls_buckets.map(&:name)
    end

    def download_all(to:)
      client.download_dir(bucket:, to:, from: path)
    end

    def upload_all(from:)
      client.upload_dir(bucket:, from:, to: path)
    end

    def delete_deleted_files(from:)
      client.ls(bucket:, prefix: path).each do |fo|
        local_path = ::Pathname.new(from).join(fo.key).to_s.sub(path, '').sub('//', '/')
        fo.delete unless ::File.exist?(local_path)
      end
    end

    def bucket_exists?
      client.bucket_exists?(bucket:)
    end

    def create_bucket_if_not_exists!
      return if bucket_exists?

      create_bucket!

      1.upto(15) do # wtf minio?
        if bucket_exists?
          allow_public_read!
          break
        end
        sleep(1)
      end
    end

    def create_bucket!
      client.create_bucket(bucket:)
    end

    def allow_public_read!
      client.set_allow_public_read(bucket:)
    end

    def ls # rubocop: disable Metrics/AbcSize
      return [] unless bucket_exists?

      fn = path.end_with?('/') ? path : path + '/'

      client.ls(bucket:, prefix: path).map do |i|
        FileItem.new(
          key: i.key.sub(fn, ''),
          size: i.size,
          last_modified_at: i.last_modified,
          url: config.url_to_public(i.public_url)
        )
      end
    end
  end
end

app/controllers/broadcasts/repository.rb
module Broadcasts
  class Repository < ::Broadcasts::BaseBroadcast
    def update # rubocop: disable Metrics/MethodLength
      ::Turbo::StreamsChannel.broadcast_update_later_to(
        model,
        target: dom_id(model),
        partial: 'repositories/repository_show',
        locals: { repository: model }
      )

      ::Turbo::StreamsChannel.broadcast_replace_later_to(
        model.user,
        target: dom_id(model, :publishing_status),
        partial: 'repositories/publishing_status',
        locals: { repository: model }
      )

      ::Turbo::StreamsChannel.broadcast_replace_later_to(
        model.project,
        target: dom_id(model, :publishing_status),
        partial: 'repositories/publishing_status',
        locals: { repository: model }
      )
    end

    def destroy
      ::Turbo::StreamsChannel.broadcast_remove_to(:repositories, target: dom_id(model))
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ::ApplicationController
  def index
    @repositories = current_user.repositories.includes(:project)

    breadcrumb.add('Repositories')
  end

  def show # rubocop: disable Metrics/AbcSize
    @repository = find_repository

    breadcrumb.add('Repositories', repositories_path)
    breadcrumb.add(@repository.distro.name)
    breadcrumb.add(@repository.project.name, project_path(@repository.project))
    breadcrumb.add(@repository.id)
  end

  def destroy
    find_repository.destroy!
    redirect_to(repositories_path, notice: 'Repository has been successfully deleted')
  end

  private

  def find_repository
    current_user.repositories.find(params[:id])
  end
end

app/views/repositories/_depricated_note.html.erb
<%# locals: (distro:) -%>

<% if distro.deprecated? %>
  <span class="text-warning">Deprecated
    <%= link_to deprecated_distro_path_path(distro.url_safe_id) do %>
      <i class="bi bi-question-circle-fill"></i>
    <% end %>
  </span>
<% end %>

app/views/repositories/_files.html.erb
<%# locals: (storage:) -%>

<% if storage.bucket_exists? %>
  <div>Storage url <span class="font-monospace bg-body-tertiary"><%= storage.url %></span></div>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">File</th>
        <th scope="col">Size</th>
        <th scope="col">Modified at</th>
      </tr>
    </thead>

    <tbody>

      <% storage.ls.each do |fo| %>
        <tr>
          <td><%= link_to(fo.key, fo.url) %></td>
          <td><%= number_to_human_size(fo.size) %></td>
          <td><%= fo.last_modified_at %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
<% else %>
  <div class="text-danger">Storage bucket '<%= storage.bucket %>' does not exists.</div>
<% end %>

app/views/repositories/_gpg_key.html.erb
<%# locals: (repository:) -%>

<div class="bg-body-tertiary p-2 rounded-2">
  <pre><%= repository.gpg_key.public_info.strip %></pre>
</div>
<% if repository.with_own_gpg_key? %>
  <%= link_to 'Manage', repository_index_gpg_key_path(repository), class: 'link-secondary m-1' %>
<% else %>
  <div class="text-secondary fw-light">The respository doesn't have its own GPG key and uses key from your account</div>
  <%= link_to "Create repository-specific key", repository_index_gpg_key_path(repository), class: 'link-secondary me-2' %>
  <%= link_to "Manage account's GPG key", index_gpg_key_path, class: 'link-secondary me-2' %>
<% end %>

app/views/repositories/_publishing_status.html.erb
<%# locals: (repository:) -%>

<span id="<%= dom_id(repository, :publishing_status) %>">

  <% case repository.publish_status %>
  <% when 'published' %>
    <i class="bi bi-check-circle-fill text-success m-1"></i>
    <span>Published <span><%= time_ago_in_words(repository.published_at) %> ago</span></span>
  <% when 'pending' %>
    <% if repository.last_publish_error %>
      <i class="bi bi-exclamation-circle-fill text-danger m-1"></i>
      <span>Last publish error</span>
    <% else %>
      <i class="bi bi-alarm-fill m-1"></i>
      <span>Pending publish</span>
    <% end %>
  <% when 'publishing' %>
    <span class="spinner-border spinner-border-sm m-1" aria-hidden="true"></span>
    <span>Publishing...</span>
  <% end %>

</span>

app/views/repositories/_repository_show.html.erb
<%# locals: (repository:) -%>

<h5>
  Repository for <%= repository.distro.name %>
  <small class="text-body-secondary">
    <%= link_to repository.project.name, project_path(repository.project) %> project
  </small>
</h5>

<div class="container pt-3">
  <div class="pb-3">
    <%= render partial: 'repositories/publishing_status', locals: { repository: repository } %>
  </div>

  <% if repository.last_publish_error %>
    <div class="pb-3">
      <h6 class="text-danger">
        Last publish error
        <small class="text-body-secondary">updated <%= time_ago_in_words(repository.updated_at) %> ago</small>
      </h6>
      <pre class="pre-line-wrap"><%= repository.last_publish_error %></pre>
    </div>
  <% end %>

  <div class="pt-3">
    <%= render partial: 'repositories/files', locals: { storage: repository.storage } %>
  </div>

  <div class="pt-3">
    <h6>GPG key</h6>
    <%= render partial: 'repositories/gpg_key', locals: { repository: repository } %>
  </div>

  <div class="pt-3">
    <%= link_to package_install_path(repository.user.slug, repository.project.slug, active: repository.distro.id, anchor: "collapse-accordion-#{dom_friendly(repository.distro.id)}"), class: 'btn btn-link', target: '_blank' do %>
      <i class="bi bi-download me-2"></i> Public download page
    <% end %>
  </div>

  <div class="pt-3">
    <a class="btn btn-link link-danger" href="#" data-bs-toggle="modal" data-bs-target="#delete_repository_modal">Delete repository</a>
  </div>

  <div class="modal fade" id="delete_repository_modal" tabindex="-1" aria-labelledby="delete_repository_modal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <p>
            Deleting the respository will also delete all files in the bucket. A new repository will be created upon sources fetch if there is a config for it.
          </p>

          <p class="text-warning">
            This operation cannot be undone.
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= button_to 'Yes, delete this repository', repository_path(repository), method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/repositories/index.html.erb
<%= turbo_stream_from current_user %>

<h5>Repositories</h5>

<div class="container pt-2">
  <% @repositories.ordered.group_by { |repo| repo.distro.family }.each do |family, repos| %>
    <div class="row pt-3 pb-3 align-items-center">
      <div class="col-md-auto">
        <%= render partial: 'distro_icon', locals: { family: family, size: 64 } %>
      </div>

      <div class="col">
        <div class="card-group">

          <% repos.group_by { |repo| repo.distro }.each do |d, repos_for_distro| %>
            <div class="card">
              <div class="card-body">
                <h6 class="card-title"><%= d.name %> <small class="text-secondary"><%= d.arch %></small></h6>
                <%= render partial: 'depricated_note', locals: { distro: d } %>

                <ul class="list-group list-group-flush">
                  <% repos_for_distro.sort_by { |repo| repo.created_at }.each do |repo| %>
                    <li class="list-group-item">
                      <%= link_to repo.project.name, repository_path(repo) %>
                      <div class="text-body-secondary fw-light">
                        <%= render partial: 'repositories/publishing_status', locals: { repository: repo } %>
                      </div>
                    </li>
                  <% end %>
                </ul>

              </div>
            </div>
          <% end %>

        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/repositories/show.html.erb
<%= turbo_stream_from @repository %>

<div id="<%= dom_id(@repository) %>">
  <%= render partial: 'repositories/repository_show', locals: { repository: @repository } %>
</div>