config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

::Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  root 'projects#index'

  mount ::Sidekiq::Web => '/sidekiq', constraints: ::Session::RouteConstraint.new(:root?)

  %i[about docs home transparency privacy].each do |link|
    direct "links_#{link}" do |options|
      ::APP_SETTINGS.dig(:links, link) || options[:fallback] || '#'
    end
  end

  concern :gpg_keys do
    get 'gpg_key', to: 'gpg_keys#index', as: :index_gpg_key
    post 'gpg_key/generate', to: 'gpg_keys#generate', as: :generate_gpg_key
    post 'gpg_key/upload', to: 'gpg_keys#upload', as: :upload_gpg_key
    delete 'gpg_key/destroy', to: 'gpg_keys#destroy', as: :destroy_gpg_key
  end

  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy] do
    delete 'destroy_all_but_current', on: :collection
  end
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[edit create]
    resource :password_reset,     only: %i[new edit create update]
    resource :account,            only: %i[show update]
  end

  scope '/account' do
    concerns :gpg_keys
  end

  namespace :agent_api do
    post '/', to: 'api#call'
    # get '/sources_tarball/:task_id', to: 'api#sources_tarball', as: 'download_sources_tarball'
    post '/artefacts/:task_id', to: 'api#upload_artefact', as: 'upload_artefact'
  end

  resources :projects do
    resources :ssh_keys, only: %i[create] do
      post :copy, on: :collection
    end
    resources :sources, only: %i[index create]
    resources :webhooks, only: %i[index create show new update destroy]
    resource :custom_repository_storage, only: %i[create update show destroy]
  end

  resources :agents
  resources :tasks, only: %i[index show create destroy] do
    get 'log', on: :member
    post 'cancel', on: :member
    post 'publish', on: :member
  end
  resources :repositories, only: %i[index show destroy] do
    concerns :gpg_keys
  end

  get ':user_slug/:project_slug', to: 'installs#index', as: 'package_install'
  get ':user_slug/:project_slug/install', to: redirect('%{user_slug}/%{project_slug}')

  post 'inbound_webhooks/:key', to: 'inbound_webhooks#trigger', as: 'trigger_webhook'

  ::PagesController::ALL.each do |page|
    get page, to: "pages##{page}", as: "pages_#{page}"
  end
  get 'distros/deprecated/:id', to: 'pages#deprecated_distro', as: :deprecated_distro_path
end

app/models/task.rb
class Task < ::ApplicationRecord
  belongs_to :project, class_name: '::Project'
  belongs_to :agent, class_name: '::Agent', optional: true
  has_one :user, class_name: '::User', through: :project
  has_many :artefacts, class_name: '::Task::Artefact', dependent: :destroy
  has_many :repositories, ->(task) { where(distro_id: task.distro_ids) }, through: :project, class_name: '::Repository'
  has_one :log, class_name: '::Task::Log', dependent: :destroy
  has_one :stat, class_name: '::Task::Stat', dependent: :destroy

  has_one_attached :sources

  enum :state, %w[pending_fetch pending_build running finished cancelled failed].index_with(&:itself), default: 'pending_fetch'

  broadcast_with ::Broadcasts::Task

  attribute :distro_ids, :string, array: true, default: -> { ::Distro.ids }

  scope :by_distro, ->(distro) { where('? = ANY(distro_ids)', distro) }

  validates :distro_ids, presence: true
  validates_with ::Distro::DistrosValidator
  validates :sources, presence: true, unless: -> { pending_fetch? }

  before_create { build_log }

  Progress = ::Data.define(:done, :failed, :total) do
    def to_s = "#{done.size + failed.size}/#{total.size}"
  end

  def append_log(text)
    touch # rubocop: disable Rails/SkipsModelValidations
    log.append(text)
  end

  def save_stats(stats)
    touch # rubocop: disable Rails/SkipsModelValidations
    stats ||= {}
    stats = ::ActionController::Parameters.new(stats) unless stats.is_a?(::ActionController::Parameters)
    stat = stat || build_stat
    stat.update(stats.except(:task_id).permit!)
  end

  def distros
    ::Distro.by_ids(distro_ids)
  end

  def finish!
    success = unfinished_distros.empty? && artefacts.all?(&:success?)
    update!(state: success ? 'finished' : 'failed', finished_at: ::Time.now.utc)
  end

  def unfinished_distros
    (distro_ids.to_set - artefacts.map(&:distro).to_set).map { |i| ::Distro[i] }
  end

  def duration
    return if !started_at || !finished_at

    ::Duration.build(finished_at - started_at)
  end

  def agent_limits
    return if agent&.user.present? # private agents have no limits

    # if user.root?
    {
      memory: '16g',
      cpus: '6',
      pids: 50_000,
      execute_timeout: 86_400
    }
  end

  def secrets
    project.secrets.to_h
  end

  def progress
    d = log.distro_ids
    Progress.new(done: d.successfull.sort, failed: d.failed.sort, total: distro_ids.sort)
  end

  def copy_project_sources!
    sources.attach(project.sources_tarball.tarball.blob) if project.sources_verified?
  end

  def reset_progress!
    transaction do
      log&.update!(text: '')
      update!(state: 'pending_build', agent_id: nil)
    end
  end

  def log_artefact(distro_id)
    artefacts.failed.where(distro: distro_id).find { _1.filename.end_with?('.log') }
  end
end

app/models/task/artefact.rb
class Task
  class Artefact < ::ApplicationRecord
    belongs_to :task, class_name: '::Task'

    has_one_attached :attachment

    scope :failed, -> { where(error: true) }
    scope :successful, -> { where.not(error: true) }

    validates :distro, presence: true, inclusion: { in: ::Distro.ids }
    validates :attachment, presence: true

    def filename
      attachment.filename.to_s
    end

    def filetype
      attachment.filename.extension
    end

    def distro_object
      ::Distro[distro]
    end

    def success?
      !error
    end

    def download(to:, overwrite_existing: false) # rubocop: disable Metrics/MethodLength
      ::FileUtils.mkdir_p(to)

      fpath = ::Pathname.new(to).join(filename)
      if ::File.exist?(fpath)
        if overwrite_existing
          ::File.delete(fpath)
        else
          raise "file #{fpath} already exists"
        end
      end

      ::File.open(fpath, 'wb') do |f|
        f.write(attachment.download)
      end
    end
  end
end

app/models/task/log.rb
class Task
  class Log < ::ApplicationRecord
    belongs_to :task, class_name: '::Task'

    before_save :set_progress_distro_ids, if: :text_changed?

    DistroIds = ::Data.define(:successfull, :failed) do
      def self.build(string)
        new(
          successfull: extract(string, /successfully finished build for (.+) in/),
          failed: extract(string, /failed build for (.+) in/)
        )
      end

      def self.extract(string, regex)
        (string.scan(regex).flatten.compact & ::Distro.ids).freeze
      end
    end

    def append(atext) # rubocop: disable Metrics/MethodLength, Metrics/AbcSize
      return if atext.blank?

      query = "text = CONCAT(text, ?)"
      args = [atext]

      d = DistroIds.build(atext)
      if d.successfull.any?
        query += ", successfull_distro_ids = ARRAY_CAT(successfull_distro_ids, ARRAY[?])"
        args << d.successfull
      end
      if d.failed.any?
        query += ", failed_distro_ids = ARRAY_CAT(failed_distro_ids, ARRAY[?])"
        args << d.failed
      end

      self.class.where(id: id).update_all([query, *args]) # rubocop: disable Rails/SkipsModelValidations
      ::Broadcasts::TaskLog.new(self).append(atext)
    end

    def distro_ids
      DistroIds.new(successfull_distro_ids, failed_distro_ids)
    end

    private

    def set_progress_distro_ids
      self.successfull_distro_ids, self.failed_distro_ids = DistroIds.build(text).deconstruct
    end
  end
end

app/models/task/scheduler.rb
class Task
  class Scheduler # rubocop: disable Metrics/ClassLength
    attr_reader :agent

    Command = ::Data.define(:command, :task) do
      def to_hash(view_context) # rubocop: disable Metrics/AbcSize, Metrics/MethodLength
        result = { command: command }
        if task
          result[:task] = {
            id:                   task.id,
            sources_tarball_url:  task.sources.url(expires_in: 3.days),
            upload_artefact_url:  view_context.agent_api_upload_artefact_url(task.id),
            distros:              task.distro_ids,
            limits:               task.agent_limits,
            secrets:              task.secrets,
            build_config_path:    task.project.sources.config_path
          }
        end
        result.freeze
      end
    end

    def initialize(agent)
      @agent = agent
    end

    def call(payload) # rubocop: disable Metrics/AbcSize, Metrics/MethodLength
      state = payload.fetch(:state)

      if state == 'idle'
        reschedule
        return schedule
      end

      log = payload[:livelog]
      stats = payload[:stats]
      task_id = payload.fetch(:task).fetch(:id)

      task = agent.tasks.find_by(id: task_id)
      return stop_command if !task

      if task.cancelled?
        save_log_stats(task, log, stats)
        return stop_command
      end

      if state == 'busy'
        busy(task, log)
      elsif state == 'finished'
        finish(task, log, stats)
      end
    end

    private

    def stop_command
      Command['stop', nil]
    end

    def schedule
      ::ApplicationRecord.transaction(isolation: :serializable) do
        task = atomic_task_fetch
        if task
          Command['start', task]
        else
          raise ::ActiveRecord::Rollback
        end
      end
    end

    def atomic_task_fetch # rubocop: disable Metrics/MethodLength, Metrics/AbcSize
      sql = <<~SQL.squish
        UPDATE
          tasks
        SET
          state = 'running',
          agent_id = #{agent.id},
          started_at = NOW() at time zone 'utc'
        WHERE id = (
          SELECT t.id FROM tasks t
          JOIN projects p ON t.project_id = p.id
          JOIN agents a ON (p.user_id = a.user_id OR a.user_id ISNULL)
          WHERE
            t.state = 'pending_build' AND
            a.id = #{agent.id} AND
            t.distro_ids::varchar[] && ARRAY[#{agent.supported_distros.map { |d| "'#{d.id}'" }.join(',')}]::varchar[]
          ORDER BY t.created_at ASC LIMIT 1
          FOR UPDATE
        ) RETURNING *;
      SQL
      pgresult = ::ApplicationRecord.connection.execute(sql)
      return if pgresult.values.empty?

      fields = pgresult.fields
      ::Task.instantiate(fields.zip(pgresult.values.sole).to_h)
    end

    def reschedule
      # agent restarted or something else happened that it's no idle, but has running tasks
      if agent.tasks.running.exists?
        agent.reschedule_all_tasks!
      end
    end

    def busy(task, log)
      ::ApplicationRecord.transaction do
        task.append_log(log)
        task.running!
      end
    end

    def finish(task, log, stats)
      ::ApplicationRecord.transaction do
        task.append_log(log)
        task.save_stats(stats)
        task.finish!
      end
      ::RepositoryPublishJob.start(task)
    end

    def save_log_stats(task, log, stats)
      ::ApplicationRecord.transaction do
        task.append_log(log) if log
        task.save_stats(stats) if stats
      end
    end
  end
end

app/models/task/starter.rb
class Task
  class Starter
    def initialize(project, skip_fetch: false, distro_ids: nil)
      @distro_ids = distro_ids || project.distro_ids.presence || ::Distro.active_ids
      @distro_ids &= ::Distro.active_ids
      @project = project
      @skip_fetch = skip_fetch
    end

    def call
      create_source_tarball_if_not_exists

      tasks = build_tasks
      if tasks.all?(&:save) && tasks.all?(&:pending_fetch?)
        ::SourcesFetchJob.start(project, tasks)
      end
      tasks
    end

    def sources_fetched(tasks)
      tasks.each do |task|
        task.copy_project_sources!
        task.update!(state: 'pending_build', distro_ids: task.distro_ids & distro_ids)
      end
    end

    private

    attr_reader :project, :skip_fetch, :distro_ids

    def build_tasks # rubocop: disable Metrics/MethodLength
      tasks = distro_ids.map { project.tasks.build(distro_ids: [it]) }
      if skip_fetch && project.sources_verified?
        tasks.each do |task|
          task.state = 'pending_build'
          task.copy_project_sources!
        end
      else
        tasks.each do |task|
          task.state = 'pending_fetch'
        end
      end
      tasks
    end

    def create_source_tarball_if_not_exists
      return if project.sources_tarball

      project.create_sources_tarball!
      project.unverified!
    end
  end
end

app/models/task/stat.rb
class Task
  class Stat < ::ApplicationRecord
    belongs_to :task, class_name: '::Task'
  end
end

app/controllers/broadcasts/task.rb
module Broadcasts
  class Task < ::Broadcasts::BaseBroadcast
    def create
      ::Turbo::StreamsChannel.broadcast_prepend_later_to(
        model.user,
        target: 'tasks',
        partial: 'tasks/task',
        locals: { task: model, highlight: true }
      )

      ::Broadcasts::Project.new(model.project).update
    end

    def update # rubocop: disable Metrics/MethodLength, Metrics/AbcSize
      ::Turbo::StreamsChannel.broadcast_replace_later_to(
        model.user,
        target: dom_id(model),
        partial: 'tasks/task',
        locals: { task: model }
      )

      ::Turbo::StreamsChannel.broadcast_update_later_to(
        model,
        target: dom_id(model),
        partial: 'tasks/task_show',
        locals: { task: model }
      )

      ::Turbo::StreamsChannel.broadcast_update_later_to(
        model,
        target: dom_id(model, :state_icon),
        partial: 'tasks/state_icon',
        locals: { task: model }
      )

      ::Broadcasts::Project.new(model.project).update
    end

    def destroy
      ::Turbo::StreamsChannel.broadcast_remove_to(:tasks, target: dom_id(model))
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ::ApplicationController
  def index # rubocop: disable Metrics/AbcSize
    # if params.key?(:project_id) && params[:project_id].blank?
    # redirect_to(tasks_path)
    # end
    tasks = if project
              project.tasks
            else
              current_user.tasks
            end
    tasks = tasks.by_distro(params[:distro]) if params[:distro].present?
    tasks = tasks.where(state: params[:state]) if params[:state].present?
    @pagination, @tasks = ::Pagination.new(tasks.order(created_at: :desc), self).call

    breadcrumb.add('Tasks')
  end

  def show
    @task = task

    breadcrumb.add('Tasks', tasks_path)
    breadcrumb.add("Task #{@task.id}")
  end

  def create # rubocop: disable Metrics/AbcSize, Metrics/MethodLength, Metrics/PerceivedComplexity
    tasks = ::Task::Starter.new(project, skip_fetch: params[:skip_fetch] == 'true', distro_ids: params[:distro_ids].presence).call
    if tasks.empty?
      redirect_back_or_to(tasks_path, alert: 'Pending task already exists, skipping')
    elsif tasks.all?(&:valid?)
      if params[:no_redirect] == 'true'
        redirect_back_or_to(tasks_path)
      elsif tasks.size == 1
        redirect_to(tasks_path(project_id: project.id, highlight: tasks.sole.id))
      else
        redirect_to(tasks_path(project_id: project.id))
      end
    else
      redirect_back_or_to(tasks_path, alert: "Error creating CI task: #{task.find(&:invalid?).errors.full_messages.to_sentence}")
    end
  end

  def destroy
    task.destroy!
    redirect_to(tasks_path, notice: 'Task has been successfully deleted')
  end

  def cancel
    task.cancelled!
    redirect_to(tasks_path, notice: 'Task has been successfully cancelled')
  end

  def log # rubocop: disable Metrics/AbcSize, Metrics/MethodLength
    respond_to do |format|
      format.text do
        render(plain: task.log.text)
      end
      format.html do
        @log = task.log

        breadcrumb.add('Tasks', tasks_path)
        breadcrumb.add(task.id, task_path(task))
        breadcrumb.add('Log')
      end
    end
  end

  def publish
    ::RepositoryPublishJob.start(task)
    redirect_to(task_path(task), notice: 'Repository publish job has been successfully started')
  end

  private

  def project
    @project ||= current_user.projects.find_by(id: params[:project_id]) # rubocop: disable Rails/FindByOrAssignmentMemoization
  end

  def task
    @task ||= current_user.tasks.find(params[:id])
  end
end

app/views/tasks/_artefacts.html.erb
<%# locals: (task:) -%>

<div class="vstack gap-3">

  <% task.artefacts.group_by(&:distro).sort_by { |i| d = ::Distro[i.first]; [d.family, d.name] }.each do |distro, afacts| %>
    <div class="card" id="artefacts-<%= dom_friendly(distro)%>">
      <div class="card-header">
        <div class="row">
          <div class="col-md-auto">
            <%= render partial: 'distro_icon', locals: { family: ::Distro[distro].family, size: 24 } %>
            <%= ::Distro[distro].name %>
          </div>
          <div class="col">
          <% if afacts.any?(&:error?) %>
            <%= button_to tasks_path(project_id: task.project.id, distro_ids: [distro], skip_fetch: true), method: :post, class: 'btn btn-link' do %>
              <i class="bi bi-exclamation-triangle-fill text-danger me-1"></i> Retry
            <% end %>
          <% end %>
          </div>
        </div>
      </div>

      <div class="card-body">
        <table class="table table-sm">

          <thead>
            <tr>
              <th scope="col">File</th>
              <th scope="col">Content type</th>
              <th scope="col">Size</th>
              <th scope="col">Created at</th>
            </tr>
          </thead>

          <tbody>
            <% afacts.each do |afact| %>
              <tr>
                <td><%= link_to afact.filename, rails_blob_path(afact.attachment.blob, disposition: 'attachment') %></td>
                <td><%= afact.attachment.content_type %></td>
                <td><%= number_to_human_size(afact.attachment.byte_size) %></td>
                <td><%= afact.attachment.blob.created_at %></td>
              </tr>
            <% end %>

          </tbody>
        </table>

      </div>
    </div>
  <% end %>

</div>

app/views/tasks/_state_icon.html.erb
<%# locals: (task:) -%>

<span class="m-1">
  <% case task.state %>
  <% when 'running' %>
    <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
  <% when 'pending_build' %>
    <i class="bi bi-alarm-fill"></i>
  <% when 'pending_fetch' %>
    <i class="bi bi-cloud-arrow-down-fill"></i>
  <% when 'finished' %>
    <i class="bi bi-check-circle-fill text-success"></i>
  <% when 'cancelled' %>
    <i class="bi bi-exclamation-diamond-fill text-warning"></i>
  <% when 'failed' %>
    <% if task.artefacts.successful.exists? %>
      <i class="bi bi-exclamation-triangle-fill text-warning"></i>
    <% else %>
      <i class="bi bi-exclamation-triangle-fill text-danger"></i>
    <% end %>
  <% end %>
</span>

app/views/tasks/_state_text.html.erb
<%# locals: (task:) -%>

<%= task.state.humanize %>
<% if task.running? %>
  <%= task.progress.to_s %>
<% end %>
<% if !task.pending_fetch? && !task.pending_build? && task.agent && task.agent.user && current_user == task.agent.user %>
  <span>on <%= link_to task.agent.name, agent_path(task.agent), class: 'link-secondary' %></span>
<% end %>
<% if task.failed? %>
  <% failed_artefacts = task.artefacts.failed %>
  <% unfinished_distros = task.unfinished_distros %>

  <% if failed_artefacts.any? %>
    <span> build for </span>
    <% failed_artefacts.each_with_index do |a, index| %>
      <a class="link-secondary" href="#artefacts-<%= dom_friendly(a.distro) %>"><%= a.distro_object.name %></a>
    <% end %>
  <% end %>

  <% if unfinished_distros.any? %>
    <span> no artefacts for distros </span>
    <% task.unfinished_distros.each do |d| %>
      <span class="fw-bolder text-decoration-underline"><%= d.name %></span>
    <% end %>
  <% end %>

<% end %>
<%= time_ago_in_words(task.updated_at) %> ago

app/views/tasks/_task.html.erb
<%# locals: (task:, highlight: false) -%>

<li class="list-group-item <%= highlight ? 'highlight-animate-added-item' : '' %>" id="<%= dom_id(task) %>">
  <div class="row">

    <div class="col">
      <%= link_to "##{task.id}", task_path(task.id) %>
      <%= render partial: 'tasks/state_icon', locals: { task: task } %>
      <%= task.state.humanize %>
      <% if task.running? %>
        <%= task.progress.to_s %>
      <% end %>
      <% if task.failed? && task.artefacts.successful.exists? %>
        partially
      <% end %>
    </div>

    <div class="col text-secondary">
      <% case task.state %>
      <% when 'running' %>
        started <%= time_ago_in_words(task.started_at) %> ago
      <% when 'pending_fetch', 'pending_build' %>
        <%= time_ago_in_words(task.created_at) %> ago
      <% when 'finished', 'failed' %>
        <%= time_ago_in_words(task.finished_at) %> ago
      <% when 'cancelled' %>
        <%= time_ago_in_words(task.updated_at) %> ago
      <% end %>
    </div>

    <div class="col text-secondary">
      <%= task.duration&.humanized %>
    </div>

    <div class="col">
      <%= link_to task.project.name, project_path(task.project.id), class: 'link link-secondary pe-3' %>
    </div>

    <div class="col">
      <% task.distros.map(&:family).uniq.each do |df| %>
        <%= render partial: 'distro_icon', locals: { family: df, size: 16 } %>
      <% end %>
    </div>

  </div>
</li>

app/views/tasks/_task_show.html.erb
<%# locals: (task:) -%>

<h5>
  Task #<%= task.id %>
  <small class="text-body-secondary">
    created <%= time_ago_in_words(task.created_at) %> ago for
    <%= link_to task.project.name, project_path(task.project), class: 'link-secondary' %>
    project
  </small>
</h5>

<div class="pb-3 text-secondary">
  <%= render partial: 'tasks/state_icon', locals: { task: task } %>
  <%= render partial: 'tasks/state_text', locals: { task: task } %>
</div>

<% if task.sources.present? %>
  <%= link_to 'Sources snapshot', task.sources.url, class: 'btn btn-link btn-sm link-secondary', data: { turbo: false } %>
<% end %>

<div class="container pt-1">

  <div class="pt-1 pb-3">
    <h6>Distros</h6>
    <% task.distros.each do |d| %>
      <% if task.progress.done.include?(d.id) %>
        <i class="bi bi-check-circle-fill text-success"></i>
      <% elsif task.progress.failed.include?(d.id) %>
        <i class="bi bi-exclamation-triangle-fill text-danger"></i>
      <% end %>
      <%= d.name %>
      <% if task.progress.failed.include?(d.id) %>
        <% log_artefact = task.log_artefact(d.id) %>
        <% if log_artefact.present? && log_artefact.attachment.present? &&  log_artefact.attachment.blob.present? %>
          <%= link_to 'log', rails_blob_path(log_artefact.attachment.blob) %>
        <% end %>
      <% end %>
      <br />
    <% end %>
  </div>

  <div class="pb-3">
    <%= link_to 'Log', log_task_path(task) %>
  </div>

  <% if task.stat %>
    <div class="pt-1 pb-3">
      <h6>Stats</h6>
      <div class="fw-bold">
        <span class="fw-lighter">Build time</span> <%= ::Duration.build(task.stat.build_time).humanized %>
      </div>
      <div class="fw-lighter">
        <span>Total time</span> <%= ::Duration.build(task.stat.total_time).humanized %>
      </div>
      <div class="fw-lighter">
        <span>Lock wait time</span> <%= ::Duration.build(task.stat.lockwait_time).humanized %>
      </div>
    </div>
  <% end %>

  <div class="pt-1 pb-3">
    <% if task.artefacts.exists? %>
      <h6>Artefacts</h6>
      <%= render partial: 'tasks/artefacts', locals: { task: task } %>
    <% elsif task.pending_fetch? || task.pending_build? || task.running? %>
      <h6>No artefacts yet<h6>
    <% else %>
      <h6>No artefacts<h6>
    <% end %>
  </div>

</div>

<div class="pt-3">
  <div class="btn-group" role="group" aria-label="task action buttons">
    <% if task.pending_fetch? || task.pending_build? || task.running? %>
      <%= button_to cancel_task_path(task), method: :post, class: 'btn btn-link link-danger', form: { data: { turbo_confirm: "Cancel this task?" } } do %>
        Cancel
      <% end %>
    <% end %>

    <% if task.cancelled? %>
      <%= button_to task_path(task), method: :delete, class: 'btn btn-link link-danger', form: { data: { turbo_confirm: "Delete this task?" } } do %>
        Delete
      <% end %>
    <% end %>

    <% if task.finished? || (task.failed? && task.artefacts.successful.exists?) %>
      <%= button_to publish_task_path(task), method: :post, class: 'btn btn-link link-secondary', form: { data: { turbo_confirm: "Publishing will overwrite artefacts in repositories. Continue?" } } do %>
        Publish repository
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/log.html.erb
<%= turbo_stream_from @log %>
<%= turbo_stream_from @log.task %>

<div>
  <h5>
    Log for task <%= link_to "##{@log.task.id}", task_path(@log.task) %>
    <small class="text-body-secondary">
      <span id="<%= dom_id(@log.task, :state_icon) %>">
        <%= render partial: 'tasks/state_icon', locals: { task: @log.task } %>
      </span>
    </small>
  </h5>

  <div class="container pt-1">
    <div class="pt-1 pb-2">
      <%= link_to 'Raw text', log_task_path(@log.task, format: :text) %>
    </div>

    <div data-controller="log-tail">
      <div class="card">
        <div class="overflow-auto vh-100 card-body">
          <pre id="<%= dom_id(@log, :text) %>" data-log-tail-target="log"><%= @log.text %></pre>
        </div>
      </div>

      <div class="btn-group mt-1" role="group" aria-label="log tail controls">
        <button data-action="log-tail#scrollToBottom" class="btn btn-link btn-sm"><i class="bi bi-arrow-down-short me-1"></i>Scroll to bottom</button>

        <div class="form-check ms-2 mt-2">
          <input class="form-check-input" type="checkbox" value="" id="tailEnabledCheckbox" checked data-log-tail-target="toggleAutoscrollInput">
          <label class="form-check-label" for="tailEnabledCheckbox">
            Autoscroll
          </label>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/tasks/show.html.erb
<%= turbo_stream_from @task %>

<div id="<%= dom_id(@task) %>">
  <%= render partial: 'tasks/task_show', locals: { task: @task } %>
</div>