config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

::Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  root 'projects#index'

  mount ::Sidekiq::Web => '/sidekiq', constraints: ::Session::RouteConstraint.new(:root?)

  %i[about docs home transparency privacy].each do |link|
    direct "links_#{link}" do |options|
      ::APP_SETTINGS.dig(:links, link) || options[:fallback] || '#'
    end
  end

  concern :gpg_keys do
    get 'gpg_key', to: 'gpg_keys#index', as: :index_gpg_key
    post 'gpg_key/generate', to: 'gpg_keys#generate', as: :generate_gpg_key
    post 'gpg_key/upload', to: 'gpg_keys#upload', as: :upload_gpg_key
    delete 'gpg_key/destroy', to: 'gpg_keys#destroy', as: :destroy_gpg_key
  end

  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy] do
    delete 'destroy_all_but_current', on: :collection
  end
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[edit create]
    resource :password_reset,     only: %i[new edit create update]
    resource :account,            only: %i[show update]
  end

  scope '/account' do
    concerns :gpg_keys
  end

  namespace :agent_api do
    post '/', to: 'api#call'
    # get '/sources_tarball/:task_id', to: 'api#sources_tarball', as: 'download_sources_tarball'
    post '/artefacts/:task_id', to: 'api#upload_artefact', as: 'upload_artefact'
  end

  resources :projects do
    resources :ssh_keys, only: %i[create] do
      post :copy, on: :collection
    end
    resources :sources, only: %i[index create]
    resources :webhooks, only: %i[index create show new update destroy]
    resource :custom_repository_storage, only: %i[create update show destroy]
  end

  resources :agents
  resources :tasks, only: %i[index show create destroy] do
    get 'log', on: :member
    post 'cancel', on: :member
    post 'publish', on: :member
  end
  resources :repositories, only: %i[index show destroy] do
    concerns :gpg_keys
  end

  get ':user_slug/:project_slug', to: 'installs#index', as: 'package_install'
  get ':user_slug/:project_slug/install', to: redirect('%{user_slug}/%{project_slug}')

  post 'inbound_webhooks/:key', to: 'inbound_webhooks#trigger', as: 'trigger_webhook'

  ::PagesController::ALL.each do |page|
    get page, to: "pages##{page}", as: "pages_#{page}"
  end
  get 'distros/deprecated/:id', to: 'pages#deprecated_distro', as: :deprecated_distro_path
end

app/models/project.rb
class Project < ::ApplicationRecord
  belongs_to :user, class_name: '::User', inverse_of: :projects
  has_one :sources_tarball, class_name: '::Project::SourcesTarball', dependent: :destroy
  has_many :tasks, class_name: '::Task', dependent: :destroy
  has_many :repositories, class_name: '::Repository', dependent: :destroy
  has_many :webhooks, class_name: '::Webhook', dependent: :destroy
  has_one :custom_repository_storage, class_name: '::Project::CustomRepositoryStorage', inverse_of: :project, dependent: :destroy

  encrypts :sources_private_ssh_key

  has_one_attached :logo
  removable_has_one_attached :logo

  serialize :secrets, coder: ::Project::Secrets
  encrypts :secrets
  validate { |i| i.errors.add(:secrets, 'invalid secrets') if i.secrets && !i.secrets.valid? }
  normalizes :secrets, with: -> { _1.empty? ? nil : _1 }

  enum :sources_kind, ::Project::Sources.kinds.index_with(&:itself), default: ::Project::Sources.kinds.first
  enum :sources_status, %w[unverified fetching verified].index_with(&:itself), default: 'unverified'

  validates :name, presence: true, length: { maximum: 60 }
  validates :slug, presence: true, length: { maximum: 30 }, format: { with: ::Slug.new(max_len: ::User::SLUG_MAX_LEN).regex }, uniqueness: { scope: :user_id }
  validates :sources_location, presence: true, length: { maximum: 8000 }
  validates :sources_kind, presence: true
  validates :sources_subdir, length: { maximum: 500 }, format: { without: /\..|\A\// }, allow_blank: true
  validates :sources_branch, length: { maximum: 200 }, format: { without: /\..|\A\// }, allow_blank: true
  validates :description, :upstream_url, length: { maximum: 500 }, allow_blank: true
  validates_with ::FileAttachValidator, attributes: { logo: { max_size_bytes: 128_000, mime_type_regex: /image\// } }

  before_validation if: -> { slug.blank? }, on: :create do
    self.slug = ::Slug.new(max_len: ::User::SLUG_MAX_LEN).generate(name)
  end

  broadcast_with ::Broadcasts::Project

  delegate :distros, :distro_ids, :package_name, to: :sources_tarball, allow_nil: true

  def sources
    ::Project::Sources.new(
      kind:             sources_kind,
      location:         sources_location,
      subdir:           sources_subdir,
      branch:           sources_branch,
      ssh_private_key:  sources_private_ssh_key,
      config_path:      sources_config_path
    )
  end

  def generate_ssh_keys # rubocop: disable Naming/PredicateMethod
    keys = ::SshKeygen.new.generate
    if keys
      self.sources_private_ssh_key = keys.priv
      self.sources_public_ssh_key = keys.pub
      true
    else
      false
    end
  end

  def sources_verified?
    sources_tarball.present? && verified?
  end

  def sources_verified_at
    sources_tarball&.updated_at
  end

  def create_default_repositories
    distros.map do |distro|
      repositories.find_or_create_by!(distro_id: distro.id)
    end
  end

  def sibling_projects_with_ssh_keys
    user.projects.where('id != ? AND NOT (sources_private_ssh_key IS NULL AND sources_public_ssh_key IS NULL)', id)
  end

  def repository_storage_config
    return custom_repository_storage.repository_storage_config if custom_repository_storage

    user.repository_default_storage_config.append_path(slug)
  end

  def badge
    ::Project::Badge.new(self)
  end
end

app/models/project/badge.rb
class Project
  class Badge
    delegate :url, to: :storage_config
    delegate :generate, to: :builder

    def initialize(project)
      @project = project
      @filename = "#{project.slug}.svg"
      @storage_config = project.repository_storage_config.append_path(filename)
      @builder = ::SvgBadgeBuilder.new(title:, text: build_text(project))
    end

    def generate_and_upload
      ::Dir.mktmpdir do |dir|
        builder.save(dir:, filename:)
        upload(::Pathname.new(dir).join(filename))
      end
    end

    def markdown(linkto)
      <<~MARKDOWN.strip
      [![#{title}](#{url})](#{linkto})
      MARKDOWN
    end

    private

    attr_reader :storage_config, :filename, :builder

    def upload(filepath)
      ::StorageClient.new(storage_config.client_config).upload(
        bucket: storage_config.bucket,
        from: filepath,
        key: storage_config.path,
        content_type: 'image/svg+xml'
      )
    end

    def build_text(project)
      distros = ->(pkg) { ::Distro.by_package_type(pkg).map { "'#{_1.id}'" }.join(',') }
      sql = <<~SQL.squish
      COUNT(CASE WHEN distro_id IN (#{distros['rpm']}) THEN 1 ELSE NULL END) AS rpm,
      COUNT(CASE WHEN distro_id IN (#{distros['deb']}) THEN 1 ELSE NULL END) AS deb
      SQL
      result = project.repositories.published.select(sql).to_a.sole

      "#{result.rpm} RPM #{result.deb} DEB"
    end

    def title
      'OmniPackage repositories badge'
    end
  end
end

app/models/project/custom_repository_storage.rb
class Project
  class CustomRepositoryStorage < ::ApplicationRecord
    belongs_to :project, class_name: '::Project', inverse_of: :custom_repository_storage

    validates :bucket, presence: true, format: /\A(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]\z/, uniqueness: { scope: :endpoint }
    validates :path, uniqueness: { scope: [:endpoint, :bucket] }
    validates :endpoint, :access_key_id, :secret_access_key, presence: true
    validate :reachable

    encrypts :secret_access_key

    def repository_storage_config
      ::Repository::Storage::Config.new(
        client_config: ::StorageClient::Config.new(endpoint:, region:, access_key_id:, secret_access_key:),
        bucket:,
        path:,
        bucket_public_url:
      )
    end

    private

    def reachable
      storage = ::Repository::Storage.new(repository_storage_config)
      storage.ping!
      unless storage.bucket_exists?
        errors.add(:bucket, 'does not exist')
      end
    rescue ::StandardError => e
      errors.add(:endpoint, e.message)
    end
  end
end

app/models/project/secrets.rb
class Project
  class Secrets
    class << self
      def load(payload) = new(::JSON.parse(payload.presence || '{}'))

      def dump(object)
        return if object.blank?

        object = from_env(object) if object.is_a?(::String)
        ::JSON.dump(object.to_h)
      end

      def from_env(str)
        hash = str.lines.map do |line|
          k, v = line.chomp.split('=', 2)
          [k, v]
        end.to_h
        new(hash)
      end
    end

    include ::Enumerable

    delegate :each, :empty?, to: :h

    def initialize(hash = {})
      @h = hash.to_h { |k, v| [k.to_s, v.to_s] }
    end

    def to_h = h

    def to_env
      map { |k, v| "#{k}=#{v}" }.join("\n")
    end

    def valid?
      all? { |k, v| k.present? && v.present? }
    end

    private

    attr_reader :h
  end
end

app/models/project/sources.rb
class Project
  class Sources
    class << self
      def new(**kwargs)
        kind = kwargs.delete(:kind)
        raise "unsupported sources kind '#{kwargs}'" unless kinds.include?(kind)

        klass(kind).allocate.tap { |o| o.send(:initialize, **kwargs) }
      end

      def kinds
        i = %w[git]
        i << 'localfs' if ::Rails.env.local?
        i.freeze
      end

      private

      def klass(kind)
        ::Project::Sources.const_get(kind.camelize, false)
      end
    end

    Envelop = ::Data.define(:config, :tarball)

    attr_reader :location, :subdir, :config_path

    def initialize(**kwargs)
      @location = kwargs.fetch(:location)
      @subdir = kwargs.fetch(:subdir, '')
      @config_path = kwargs[:config_path].presence || '.omnipackage/config.yml'
      raise "forbidden subdir '#{subdir}'" if subdir.start_with?('/') || subdir.include?('..')
    end

    def sync
      clone do |dir|
        tarball = ::Tempfile.new
        ::ShellUtil.compress(dir, tarball.path, excludes: tarball_excludes)
        Envelop[read_config(dir), tarball]
      end
    end

    def probe
    end

    def clone
    end

    private

    def read_config(dir)
      path = ::File.join(dir, config_path)
      raise "file '#{config_path}' does not exist" unless ::File.exist?(path)

      ::YAML.load_file(path, aliases: true)
    end

    def tarball_excludes
      %w[.git]
    end
  end
end

app/models/project/sources/git.rb
class Project
  class Sources
    class Git < ::Project::Sources
      def initialize(**kwargs)
        super
        ssh_private_key = kwargs.fetch(:ssh_private_key)
        @git = ::Git.new(ssh_private_key: ssh_private_key)
        @branch = kwargs[:branch].presence
      end

      def probe
        git.ping(location)
      end

      def clone
        dir = ::Dir.mktmpdir
        return unless git.clone(location, dir, branch: branch)

        if block_given?
          yield(::Pathname.new(dir).join(subdir).to_s)
        else
          true
        end
      ensure
        ::FileUtils.remove_entry(dir)
      end

      private

      attr_reader :git, :branch

      def tarball_excludes
        %w[.git]
      end
    end
  end
end

app/models/project/sources/localfs.rb
class Project
  class Sources
    class Localfs < ::Project::Sources
      def probe # rubocop: disable Naming/PredicateMethod
        ::File.exist?(full_location)
      end

      def clone
        if block_given?
          yield(full_location)
        else
          true
        end
      end

      private

      def full_location
        ::Pathname.new(location).join(subdir).to_s
      end
    end
  end
end

app/models/project/sources_tarball.rb
class Project
  class SourcesTarball < ::ApplicationRecord
    belongs_to :project, class_name: '::Project'
    has_many :tasks, class_name: '::Task', dependent: :destroy

    has_one_attached :tarball

    def upload_tarball(io)
      self.tarball = ::ActiveStorage::Blob.create_and_upload!(
        io:           io,
        filename:     "#{project.slug}-sources-#{::Time.now.utc.strftime('%Y%m%d-%H%M%S')}.tar.xz"
      )
      self
    end

    def distros
      return unless config

      ::Distro.by_ids(config['builds'].pluck('distro').uniq)
    end

    def distro_ids
      distros&.map(&:id)
    end

    def package_name(for_distro)
      config['builds'].find { |i| i['distro'] == for_distro }&.dig('package_name')
    end
  end
end

app/controllers/broadcasts/project.rb
module Broadcasts
  class Project < ::Broadcasts::BaseBroadcast
    def update # rubocop: disable Metrics/MethodLength
      ::Turbo::StreamsChannel.broadcast_update_later_to(
        model,
        target: dom_id(model),
        partial: 'projects/project_show',
        locals: { project: model }
      )

      ::Turbo::StreamsChannel.broadcast_update_later_to(
        model.user,
        target: dom_id(model),
        partial: 'projects/project',
        locals: { project: model }
      )
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ::ApplicationController
  def index
    @pagination, @projects = ::Pagination.new(current_user.projects.order(created_at: :desc), self).call

    breadcrumb.add('Projects')
  end

  def show
    @project = find_project

    breadcrumb.add('Projects', projects_path)
    breadcrumb.add(@project.name)
  end

  def new
    @project = build_project

    breadcrumb.add('Projects', projects_path)
    breadcrumb.add('New')

    js_variables.set(:storage_base_url, @project.user.repository_default_storage_config.url)
  end

  def edit
    @project = find_project

    breadcrumb.add('Projects', projects_path)
    breadcrumb.add(@project.name, project_path(@project))
    breadcrumb.add('Edit')
  end

  def create
    @project = build_project
    @project.assign_attributes(project_params)
    if @project.valid?
      @project.generate_ssh_keys
      @project.save!
      ::SourcesFetchJob.perform_later(@project.id)
      redirect_to(projects_path, notice: "Project #{@project.name} has been successfully created")
    else
      render(:new, status: :unprocessable_content)
    end
  end

  def update
    @project = find_project
    @project.assign_attributes(project_params.except(:slug))
    if @project.save
      if %w[sources_location sources_kind].intersect?(@project.previous_changes.keys)
        ::SourcesFetchJob.start(@project)
      end
      redirect_to(project_path(@project.id), notice: "Project #{@project.name} has been successfully updated")
    else
      render(:edit, status: :unprocessable_content)
    end
  end

  def destroy
    find_project.destroy!
    redirect_to(projects_path, notice: 'Project has been successfully deleted')
  end

  private

  def find_project
    current_user.projects.find(params[:id])
  end

  def build_project
    current_user.projects.build
  end

  def project_params
    params.expect(project: [:name, :slug, :sources_location, :sources_kind, :sources_subdir, :sources_branch, :secrets, :description, :upstream_url, :logo, :_remove_logo, :sources_config_path])
  end
end

app/views/projects/_badge.html.erb
<%# locals: (project:) -%>

<span>
  <a href="#collapseBadge" class="link-underline link-underline-opacity-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseBadge" aria-expanded="false" aria-controls="collapseBadge">
    show
  </a>
</span>

<div class="collapse" id="collapseBadge" data-controller="clipboard">
  <%= link_to package_install_path(project.user.slug, project.slug), target: '_blank' do %>
    <%= image_tag(project.badge.url, class: 'img mb-2 mt-2', alt: 'badge will be generated after publishing a repository') %>
  <% end %>

  <div class="bg-body-tertiary p-2 rounded-2">
    <pre class="pre-line-wrap" data-clipboard-target="source"><%= project.badge.markdown(package_install_url(project.user.slug, project.slug)) %></pre>
  </div>

  <div class="btn-group" role="group" aria-label="badge actions">
    <button data-action="clipboard#copy" class="btn btn-link btn-sm"><i class="bi bi-copy me-1"></i>Copy markdown</button>
  </div>
</div>

app/views/projects/_project.html.erb
<%# locals: (project:) -%>

<div>
  <div class="row">
    <div class="col-auto" style="width: 80px">
      <% if project.logo.present? %>
        <%= image_tag(url_for(project.logo), height: '64', width: '64', class: 'img', alt: 'logo') %>
      <% end %>
    </div>

    <div class="col">
      <h5>
        <%= link_to project.name, project_path(project.id), class: 'card-link' %>
      </h5>

      <div class="fw-light text-body-secondary">
        <% if project.sources_fetch_error.present? %>
          <span class="text-danger">
            Sources fetch error: <%= project.sources_fetch_error %>
          </span>
        <% end %>
      </div>

      <div>
        <%= render partial: 'projects/task_state', locals: { project: project } %>
      </div>

      <% if project.sources_verified? && %w[pending_fetch pending_build running].exclude?(project.tasks.order(:created_at).last&.state) %>
        <%= button_to 'Build now', tasks_path(project_id: project.id, no_redirect: 'true'), method: :post, class: 'btn btn-link btn-sm' %>
      <% end %>
    </div>

    <div class="col text-end">
      <span>
        <% if project.sources_verified? %>
          <%= link_to package_install_path(project.user.slug, project.slug), class: 'btn btn-link', target: '_blank' do %>
            <i class="bi bi-download me-2"></i> Public install page
          <% end %>
        <% end %>
      </span>
    </div>
  </div>

</div>

app/views/projects/_project_show.html.erb
<%# locals: (project:) -%>

<div class="row">
  <div class="col-auto">
    <h5>Project <%= project.name %></h5> <span class="fw-light text-body-secondary"><%= project.description %></span>
  </div>
  <div class="col-auto" style="width: 80px">
    <% if project.logo.present? %>
      <%= image_tag(url_for(project.logo), height: '64', width: '64', class: 'img', alt: 'logo') %>
    <% end %>
  </div>
</div>

<div class="container pt-3">
  <div class="row">
    <div class="col col-md-auto">
      <div class="pt-3">
        <h6>Sources</h6>
        <%= render partial: 'projects/sources', locals: { project: project } %>
      </div>

      <div class="pt-3">
        <h6>SSH public key</h6>
        <%= render partial: 'projects/ssh_key', locals: { project: project } %>
      </div>

      <div class="pt-3">
        <h6>Secrets</h6>
        <span>
          <a href="#collapseSecrets" class="link-underline link-underline-opacity-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSecrets" aria-expanded="false" aria-controls="collapseSecrets">
            show
          </a>
        </span>

        <div class="collapse" id="collapseSecrets">
          <small class="fw-light">Secrets will be passed to the build process via environment variables and hidden from logs. <a href="#" target="_blank">Learn more</a></small>
          <div class="bg-body-tertiary p-2 rounded-2">
            <pre><%= project.secrets.to_env %></pre>
          </div>
        </div>
      </div>

      <div class="pt-3">
        <h6>Triggers</h6>
        <%= render partial: 'projects/triggers', locals: { project: project } %>
      </div>
    </div>

    <!--<div class="col col-md-auto offset-md-1">
      <small class="fw-lighter">Preview of publicly visible project info on packages install page</small>
      <div class="card shadow rounded">
        <div class="card-body">
          <%= render partial: 'projects/public_info', locals: { project: project } %>
        </div>
      </div>
    </div>-->
  </div>

  <div class="pt-3">
    <h6>Repositories</h6>
    <div class="fw-light">
      <% if project.custom_repository_storage %>
        <span>Using custom storage</span>
      <% else %>
        <span>Using default storage</span>
      <% end %>
      <span class="font-monospace bg-body-tertiary"><%= project.repository_storage_config.url %></span>
      <br />
      <div class="btn-group pb-2" role="group" aria-label="custo repo storage config link">
        <%= link_to 'Configure custom storage', project_custom_repository_storage_path(project), class: 'btn btn-link btn-sm' %>
      </div>
    </div>

    <%= render partial: 'projects/repos', locals: { repositories: project.repositories } %>
  </div>

  <div class="pt-3">
    <h6>Download packages</h6>
    <p class="fw-light">Share link to this page with your users</p>
    <%= link_to package_install_path(project.user.slug, project.slug), class: 'btn btn-link', target: '_blank' do %>
      <i class="bi bi-download me-2"></i> Public download page
    <% end %>
  </div>

  <div class="pt-3" >
    <h6>Badge</h6>
    <%= render partial: 'projects/badge', locals: { project: project } %>
  </div>

  <div class="pt-5">
    <%= link_to 'Edit project', edit_project_path(project.id), class: 'btn btn-link' %>
    <a class="btn btn-link link-danger" href="#" data-bs-toggle="modal" data-bs-target="#delete_project_modal">Delete project</a>
  </div>

</div>


  <div class="modal fade" id="delete_project_modal" tabindex="-1" aria-labelledby="delete_project_modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <p>
          Deleting the project will also delete all respositories and files.
        </p>

        <p class="text-warning">
          This operation cannot be undone.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to 'Yes, delete this project and all repositories', project_path(project.id), method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>

</div>

app/views/projects/_public_info.html.erb
<%# locals: (project:) -%>

<div class="row">
  <div class="col-md-auto">
    <% if project.logo.present? %>
      <%= image_tag(url_for(project.logo), height: '128', width: '128', class: 'img', alt: 'logo') %>
    <% end %>
  </div>

  <div class="col-md-auto">
    <h1>Install <%= project.name %></h1>
    <blockquote class="blockquote">
      <p><%= project.description %></p>
      <% if project.upstream_url.present? %>
        <p><%= link_to project.upstream_url, project.upstream_url, target: '_blank' %></p>
      <% end %>
    </blockquote>
  </div>
</div>

app/views/projects/_repos.html.erb
<%# locals: (repositories:) -%>

<div class="vstack gap-2">
  <% repositories.ordered.group_by { |repo| repo.distro.family }.each do |family, repos| %>
    <div class="row align-items-center">
      <div class="col-md-auto m-2">
        <%= render partial: 'distro_icon', locals: { family: family, size: 48 } %>
      </div>

      <div class="col">
        <div class="card-group">
          <% repos.each do |repo| %>
            <div class="card">
              <div class="card-body">

                <h6 class="card-title">
                  <%= link_to repo.distro.name, repository_path(repo), class: 'card-link' %>
                </h6>
                <%= render partial: 'repositories/depricated_note', locals: { distro: repo.distro } %>

                <div class="card-text text-body-secondary fw-light">
                  <%= render partial: 'repositories/publishing_status', locals: { repository: repo } %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  <% end %>
</div>

app/views/projects/_ssh_key.html.erb
<%# locals: (project:) -%>

<span>
  <a href="#collapseSshKey" class="link-underline link-underline-opacity-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSshKey" aria-expanded="false" aria-controls="collapseSshKey">
    show
  </a>
</span>

<div class="collapse" id="collapseSshKey" data-controller="clipboard">
  <small class="fw-light">Add this key to your sources repository with read only access. Usually these types of keys called "deployment keys" or something like that.</small>
  <div class="bg-body-tertiary p-2 rounded-2">
    <pre class="pre-line-wrap" data-clipboard-target="source"><%= project.sources_public_ssh_key %></pre>
  </div>

  <div class="btn-group" role="group" aria-label="ssh key manage">
    <button data-action="clipboard#copy" class="btn btn-link btn-sm"><i class="bi bi-copy me-1"></i>Copy to clipboard</button>

    <button data-bs-toggle="modal" data-bs-target="#copy_ssh_key_modal" class="btn btn-link btn-sm link-warning">Copy key from another project</button>

    <%= button_to 'Generate new key', project_ssh_keys_path(project.id), method: :post, class: 'btn btn-link btn-sm link-danger', form: { data: { turbo_confirm: "You will have to add newly generated key to the sources repository. Continue?" } } %>
  </div>
</div>

<div class="modal fade" id="copy_ssh_key_modal" tabindex="-1" aria-labelledby="copyKeyModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <%= form_with(url: copy_project_ssh_keys_path(project), method: :post) do |f| %>
        <div class="modal-header">
          <h5 class="modal-title">Copy SSH key from another project</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
          <%= f.collection_select(
            :from_project_id,
            project.sibling_projects_with_ssh_keys,
            :id,
            :name,
            { include_blank: false },
            { class: 'form-select form-select-sm' }
          )%>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Save', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_task_state.html.erb
<%# locals: (project:) -%>

<span id="<%= dom_id(project, :task_state) %>">
  <%- last_task = project.tasks.order(:created_at).last %>
  <% if last_task %>
    <span class="fw-light text-body-secondary">
      Last build
    </span>
    <%= render partial: 'tasks/state_icon', locals: { task: last_task } %>
    <%= link_to task_path(last_task), class: 'link fw-light' do %>
      <%= time_ago_in_words(last_task.updated_at) %> ago
    <% end %>
  <% end %>
</span>

app/views/projects/_triggers.html.erb
<%# locals: (project:) -%>

<div class="btn-group" role="group" aria-label="ci manage">
  <% if project.sources_verified? %>
    <%= button_to 'Build now', tasks_path(project_id: project.id, skip_fetch: 'true'), method: :post, class: 'btn btn-link btn-sm' %>
  <% end %>
  <%= link_to 'Webhooks', project_webhooks_path(project), class: 'btn btn-link btn-sm' %>
  <%= link_to 'Tasks', tasks_path(project_id: project.id), class: 'btn btn-link btn-sm' %>
</div>

app/views/projects/index.html.erb
<%= turbo_stream_from current_user %>

<h5>Projects</h5>

<div class="container pt-3">
  <div class="vstack gap-5">
    <% @projects.each do |project| %>
      <div id="<%= dom_id(project) %>">
        <%= render partial: 'project', locals: { project: project } %>
      </div>
    <% end %>
  </div>

  <div class="pt-3">
    <%= render partial: 'pagination', locals: { pagination: @pagination } %>
  </div>

  <div class="pt-5">
    <%= link_to new_project_path, class: 'btn btn-primary' do %>
      <i class="bi bi-plus-circle"></i> Add new project
    <% end %>
  </div>
</div>