config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

::Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  root 'projects#index'

  mount ::Sidekiq::Web => '/sidekiq', constraints: ::Session::RouteConstraint.new(:root?)

  %i[about docs home transparency privacy].each do |link|
    direct "links_#{link}" do |options|
      ::APP_SETTINGS.dig(:links, link) || options[:fallback] || '#'
    end
  end

  concern :gpg_keys do
    get 'gpg_key', to: 'gpg_keys#index', as: :index_gpg_key
    post 'gpg_key/generate', to: 'gpg_keys#generate', as: :generate_gpg_key
    post 'gpg_key/upload', to: 'gpg_keys#upload', as: :upload_gpg_key
    delete 'gpg_key/destroy', to: 'gpg_keys#destroy', as: :destroy_gpg_key
  end

  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy] do
    delete 'destroy_all_but_current', on: :collection
  end
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[edit create]
    resource :password_reset,     only: %i[new edit create update]
    resource :account,            only: %i[show update]
  end

  scope '/account' do
    concerns :gpg_keys
  end

  namespace :agent_api do
    post '/', to: 'api#call'
    # get '/sources_tarball/:task_id', to: 'api#sources_tarball', as: 'download_sources_tarball'
    post '/artefacts/:task_id', to: 'api#upload_artefact', as: 'upload_artefact'
  end

  resources :projects do
    resources :ssh_keys, only: %i[create] do
      post :copy, on: :collection
    end
    resources :sources, only: %i[index create]
    resources :webhooks, only: %i[index create show new update destroy]
    resource :custom_repository_storage, only: %i[create update show destroy]
  end

  resources :agents
  resources :tasks, only: %i[index show create destroy] do
    get 'log', on: :member
    post 'cancel', on: :member
    post 'publish', on: :member
  end
  resources :repositories, only: %i[index show destroy] do
    concerns :gpg_keys
  end

  get ':user_slug/:project_slug', to: 'installs#index', as: 'package_install'
  get ':user_slug/:project_slug/install', to: redirect('%{user_slug}/%{project_slug}')

  post 'inbound_webhooks/:key', to: 'inbound_webhooks#trigger', as: 'trigger_webhook'

  ::PagesController::ALL.each do |page|
    get page, to: "pages##{page}", as: "pages_#{page}"
  end
  get 'distros/deprecated/:id', to: 'pages#deprecated_distro', as: :deprecated_distro_path
end

app/controllers/application_controller.rb
class ApplicationController < ::ActionController::Base
  before_action :authenticate
  before_action :require_authentication

  attr_reader :current_user, :current_session

  helper_method :current_user, :logged_in?, :current_session, :breadcrumb, :js_variables, :page_title

  private

  def breadcrumb
    @breadcrumb ||= ::Breadcrumb.new(view_context)
  end

  def sign_in(user)
    @current_session = user.sessions.create!(user_agent: request.user_agent, ip_address: request.ip)
    @current_user = user
    cookies.signed.permanent[:session_token] = { value: @current_session.id, httponly: true }
  end

  def sign_out
    cookies.delete(:session_token)
  end

  def authenticate
    @current_session = ::Session.authenticate(cookies)
    return unless @current_session

    @current_session.update(user_agent: request.user_agent, ip_address: request.ip)
    @current_user = @current_session.user
  end

  def require_authentication
    redirect_to(sign_in_path) unless logged_in?
  end

  def require_no_authentication
    redirect_to(root_path, notice: "You're already signed in") if logged_in?
  end

  def logged_in?
    current_session.present? && current_user.present?
  end

  def set_nocache
    response.headers["Cache-Control"] = "no-cache, no-store"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Mon, 01 Jan 1990 00:00:00 GMT"
  end

  def js_variables
    @js_variables ||= ::JsVariables.new
  end

  def page_title
    "OmniPackage#{breadcrumb.to_page_title_part}"
  end

  def captcha_verified?
    ::Turnstile.new.call(params['cf-turnstile-response'], request.remote_ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dom_friendly(string)
    string.to_s.downcase.gsub(/[^0-9a-z]/i, '-')
  end
end

app/views/application/_bootstrap.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

app/views/application/_breadcrumbs.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <% breadcrumb.each do |page| %>
      <% if page.active? %>
        <li class="breadcrumb-item active" aria-current="page"><%= page.name %></li>
      <% elsif page.path %>
        <li class="breadcrumb-item"><%= link_to page.name, page.path %></li>
      <% else %>
        <li class="breadcrumb-item"><%= page.name %></li>
      <% end %>
    <% end %>
  </ol>
</nav>

app/views/application/_distro_icon.html.erb
<%# locals: (family:, size:) -%>

<img src="<%= asset_path("distros/#{family}.svg") %>" alt="<%= family + ' logo' %>" width="<%= size %>px" hight="<%= size %>px">

app/views/application/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%=type == 'alert' ? 'danger' : 'success'%> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<script>
  document.querySelectorAll('.alert-dismissible').forEach(function(element) {
    setTimeout(function() {
      bootstrap.Alert.getOrCreateInstance(element).close();
    }, 10000);
  });
</script>

app/views/application/_footer.html.erb
<div class="p-3 bg-body-tertiary">
  <div class="container-fluid py-3">

    <div class="row">
      <div class="col text-center">
        <%= link_to ::APP_SETTINGS.dig(:links, :home) || root_path, target: '_blank' do %>
          <div class="mb-3">
            <img src="<%= asset_path("brand/logo_with_slogan.svg") %>" alt="logo" height="86px">
          </div>
        <% end %>
      </div>

      <div class="col text-center">
        <p><%= link_to 'About', links_about_url, class: 'link-secondary', target: '_blank' %></p>
        <p><%= link_to 'Documentation', links_docs_url, class: 'link-secondary', target: '_blank' %></p>
        <p><%= link_to 'Supported distros', pages_distros_path, class: 'link-secondary' %></p>
      </div>

      <div class="col text-center">
        <p><%= link_to 'Home page', links_home_url(fallback: root_url), class: 'link-secondary', target: '_blank' %></p>
        <p><%= link_to 'Transparency', links_transparency_url, class: 'link-secondary', target: '_blank' %></p>
        <p><%= link_to 'Privacy policy', links_privacy_url, class: 'link-secondary', target: '_blank' %></p>
      </div>
    </div>
  </div>
</div>

app/views/application/_js_variables.html.erb
<script>
  window.js_variables = <%= js_variables.to_json.html_safe %>;
</script>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-secondary">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <img src="<%= asset_path("brand/logo_symbol.svg") %>" alt="logo" height="30px">
      <% unless logged_in? %>
        OmniPackage
      <% end %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <%= render partial: 'navbar_link', locals: { path: projects_path, text: 'Projects', active: -> { params[:controller] == 'projects' } } %>
          <%= render partial: 'navbar_link', locals: { path: repositories_path, text: 'Repositories', active: -> { params[:controller] == 'repositories' } } %>
          <%= render partial: 'navbar_link', locals: { path: tasks_path, text: 'Tasks', active: -> { params[:controller] == 'tasks' } } %>
        <% end %>
      </ul>


      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item me-3">
          <%= link_to 'Documentation', links_docs_url, class: 'nav-link', target: '_blank' %>
        </li>

        <li class="nav-item dropdown me-3">
          <%= render partial: 'theme_selector' %>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown me-3">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag user_avatar_url(current_user), size: 24, class: 'img-fluid rounded' %> <%= current_user.displayed_name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end shadow">
              <li>
                <%= link_to identity_account_path, class: 'dropdown-item' do %>
                  <i class="bi bi-person-circle me-2 opacity-50"></i>
                  Account
                <% end %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to current_session, method: :delete, class: 'dropdown-item' do %>
                  <i class="bi bi-box-arrow-right me-2 opacity-50"></i>
                  Log out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", sign_in_path, class: 'btn btn-outline-success' %>
          </li>
          <li class="nav-item ms-2">
            <%= link_to "Sign up", sign_up_path, class: 'btn btn-success' %>
          </li>
      <% end %>

      </ul>

    </div>
  </div>
</nav>

app/views/application/_navbar_link.html.erb
<%# locals: (text:, path:, active:) -%>

<li class="nav-item">
  <% if active.call %>
    <%= link_to text, path, class: 'nav-link active', 'aria-current' => 'page' %>
  <% else %>
    <%= link_to text, path, class: 'nav-link' %>
  <% end %>
</li>

app/views/application/_pagination.html.erb
<%# locals: (pagination:) -%>

<% if pagination.pages > 1 %>
  <nav aria-label="pagination">
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link <%= pagination.first? ? 'disabled' : '' %>" href="<%= pagination.prev_page_link %>" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>

      <% if pagination.extended? %>
        <% 1.upto(pagination.extended_split) do |i| %>
          <li class="page-item <%= pagination.page == i ? 'active' : '' %>">
            <a class="page-link" href="<%= pagination.page_link(i) %>"><%= i %></a>
          </li>
        <% end %>

        <% if pagination.omisson? %>
          <li class="page-item"><a class="page-link">...</a></li>

          <li class="page-item active">
            <a class="page-link" href="<%= pagination.page_link(pagination.page) %>"><%= pagination.page %></a>
          </li>

          <li class="page-item"><a class="page-link">...</a></li>
        <% else %>
          <li class="page-item"><a class="page-link">...</a></li>
        <% end %>

        <% (pagination.pages - pagination.extended_split).upto(pagination.pages) do |i| %>
          <li class="page-item <%= pagination.page == i ? 'active' : '' %>">
            <a class="page-link" href="<%= pagination.page_link(i) %>"><%= i %></a>
          </li>
        <% end %>
      <% else %>
        <% 1.upto(pagination.pages) do |i| %>
          <li class="page-item <%= pagination.page == i ? 'active' : '' %>">
            <a class="page-link" href="<%= pagination.page_link(i) %>"><%= i %></a>
          </li>
        <% end %>
      <% end %>

      <li class="page-item">
        <a class="page-link <%= pagination.last? ? 'disabled' : '' %>" href="<%= pagination.next_page_link %>" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
<% end %>

app/views/application/_theme_selector.html.erb
<div data-controller="theme-selector">
  <button class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="bi bi-sun-fill opacity-70" data-theme-selector-target="currentTheme" data-theme="light"></i>
    <i class="bi bi-moon-stars-fill opacity-70" data-theme-selector-target="currentTheme" data-theme="dark"></i>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow">
    <li>
      <button data-action="theme-selector#setCurrentTheme" class="dropdown-item" data-theme-selector-target="themeButton" data-theme="light" data-theme-selector-theme-param="light">
        <i class="bi bi-sun-fill me-2 opacity-50 theme-icon"></i>
        Light
      </button>
    </li>
    <li>
      <button data-action="theme-selector#setCurrentTheme" class="dropdown-item" data-theme-selector-target="themeButton" data-theme="dark" data-theme-selector-theme-param="dark">
        <i class="bi bi-moon-stars-fill me-2 opacity-50 theme-icon"></i>
        Dark
      </button>
    </li>
    <li><hr class="dropdown-divider"></li>
    <li>
      <button data-action="theme-selector#setCurrentTheme" class="dropdown-item" data-theme-selector-target="themeButton" data-theme="auto" data-theme-selector-theme-param="auto">
        <i class="bi bi-sun me-2 opacity-50" data-theme-selector-target="preferedTheme" data-theme="light"></i>
        <i class="bi bi-moon-stars-fill me-2 opacity-50" data-theme-selector-target="preferedTheme" data-theme="dark"></i>
        Auto
      </button>
    </li>
  </ul>
</div>

app/views/application/_turnstile.html.erb
<script>
  function getTurnstileHiddenElement() {
    return document.getElementById("hidden-until-captcha-callback");
  }

  function turnstileCallback(token) {
    console.info("Turnstile success", token);
    const elem = getTurnstileHiddenElement();
    if (elem) {
      elem.removeAttribute("hidden")
    }
  }

  <% if ::Turnstile.enabled? %>
  setTimeout(() => {
    const elem = getTurnstileHiddenElement();
    if (elem) {
      elem.setAttribute("hidden", true)
    }
  }, 100);
  <% end %>
</script>

<% if ::Turnstile.enabled? %>
  <div class="cf-turnstile" data-sitekey="<%= ::Turnstile.site_key %>" data-callback="turnstileCallback"></div>
<% end %>